version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # .devcontainer ディレクトリのdocker-comopse.yml なので、1つ上のディレクトリをマウントする
      - ..:/workspaces:cached
      - nestjs_devcontainer_node_modules:/workspaces/node_modules
    command: sleep infinity

volumes:
  nestjs_devcontainer_node_modules:
